---
gitconfig_user_name: "{{ ansible_user_id }}"
gitconfig_user_email: "{{ ansible_user_id }}@{{ ansible_hostname }}.local"
gitconfig_signingkey: ""
gitconfig_signingkey_format: "gpg"
gitconfig_init_defaultBranch: "main"
gitconfig_push_autoSetupRemote: true
gitconfig_aliases: {}
# Example:
# gitconfig_aliases:
#   co: "checkout"
#   br: "branch"
#   ci: "commit"
